# Generated by Django 4.2.5 on 2023-09-21 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(choices=[('Heliopolis', 'Heliopolis'), ('Nasr City', 'Nasr City'), ('Dokki', 'Dokki'), ('New Cairo', 'New Cairo'), ('New Giza', 'New Giza')], default='New Cairo', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
